# Generated by Django 4.2.4 on 2023-09-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
      
    ]

    operations = [
       
    ]
