# Generated by Django 4.2.4 on 2023-09-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
        ('posts', '0005_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='followers.follower'),
        ),
    ]
