# Generated by Django 4.2.4 on 2023-09-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
        ('posts', '0006_post_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='followed',
        ),
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.ManyToManyField(
                blank=True, related_name='following', to='followers.follower'),
        ),
    ]
