# Generated by Django 4.2.4 on 2023-09-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visibility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visibility',
            name='post',
        ),
    ]
