# Generated by Django 4.2.4 on 2023-09-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visibility', '0002_remove_visibility_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visibility',
            options={},
        ),
        migrations.RemoveField(
            model_name='visibility',
            name='created_at',
        ),
    ]
